// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZl3qWagB_yWeQIIA9NOi-TT1DHDGYRo',
    appId: '1:1004358192671:web:d4f134caea0ba88b664f2a',
    messagingSenderId: '1004358192671',
    projectId: 'fir-sample-d3c5d',
    authDomain: 'fir-sample-d3c5d.firebaseapp.com',
    storageBucket: 'fir-sample-d3c5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCejhRNSbVW61kIzJUaOfAdzrVTrHl1q-w',
    appId: '1:1004358192671:android:0b8bdb3078f5ccc9664f2a',
    messagingSenderId: '1004358192671',
    projectId: 'fir-sample-d3c5d',
    storageBucket: 'fir-sample-d3c5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qZ-lhUAU5cZV0CWq9dMr1Jp09z7lzUo',
    appId: '1:1004358192671:ios:b1085899167f5997664f2a',
    messagingSenderId: '1004358192671',
    projectId: 'fir-sample-d3c5d',
    storageBucket: 'fir-sample-d3c5d.appspot.com',
    iosClientId: '1004358192671-qip0vdqtksl92ka4ag19bo27ghrg1j4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2qZ-lhUAU5cZV0CWq9dMr1Jp09z7lzUo',
    appId: '1:1004358192671:ios:b1085899167f5997664f2a',
    messagingSenderId: '1004358192671',
    projectId: 'fir-sample-d3c5d',
    storageBucket: 'fir-sample-d3c5d.appspot.com',
    iosClientId: '1004358192671-qip0vdqtksl92ka4ag19bo27ghrg1j4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedemo',
  );
}
